Update cluster-autoscaler-autodiscover.yaml
Trying to fix this error:
Error: INSTALLATION FAILED: 1 error occurred:
	* Deployment.apps "cluster-autoscaler" is invalid: [spec.template.spec.containers[0].name: Required value, spec.template.spec.containers[0].image: Required value]